### ISSUE TITLE
1. user can see their car

### ISSUE THREAD

**Issue by AngelaJiaNan** [AngelaJiaNan/driving-game#1]
![image](https://user-images.githubusercontent.com/90875226/140410341-b81b0463-772d-4e23-b262-ac5b26755cdf.png)

# 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [ ] add img tag racecar to HTML
- [ ] set CSS background color to match wireframe
- [ ] make sure it matches the wireframe
